# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 8
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Npm build
      run: npm run build
    - name: Chrome Extension upload & publish
      uses: Passiverecords/chrome-extension-upload-action@1.4.1
      with:
        # Auth refresh token
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
        # Extension application target id
        app-id: ${{ secrets.APP_ID }}
        # Token client id
        client-id: ${{ secrets.CLIENT_ID }}
        # Token client secret
        client-secret: ${{ secrets.CLIENT_SECRET }}
        # Name of zipped target upload file
        file-name: build.zip
        # True Or False to publish after upload
        publish: false
    - name: Bundle release
      run: npm run release
      env:
        PRIVATE_KEY: ${{ secrets.FAKE_PRIVATE_KEY }}
    - name: Upload To Github Release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "release/*.(zip|crx)"
        overwrite: true



